from __future__ import annotations

import hashlib
import json
import os
import shutil
import zipfile
from pathlib import Path

import pytest

from choicer_voicer_pack_creator.captions import refine_captions
from choicer_voicer_pack_creator.config_format import read_config
from choicer_voicer_pack_creator.exporter import PackExporter
from choicer_voicer_pack_creator.media import MediaTools
from choicer_voicer_pack_creator.models import PackProject, Segment, SourceCaption
from choicer_voicer_pack_creator.pack_io import PackImporter
from choicer_voicer_pack_creator.pack_manifest import MANIFEST_NAME, read_manifest
from choicer_voicer_pack_creator.validation import PackValidator


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.mark.integration
def test_caption_handles_retain_source_audio_outside_subtitle_window(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "source.wav"
    media.run([
        media.ffmpeg, "-v", "error", "-y", "-f", "lavfi", "-i",
        "sine=frequency=440:sample_rate=48000:duration=1.27",
        "-af", "adelay=910,apad=whole_dur=5", str(source),
    ], "Creating audio that starts before and finishes after its caption")
    cue = refine_captions(
        [SourceCaption(1, 2, "Synthetic timing fixture", "YouTube creator (en)")],
        [(0.91, 2.18)], 5,
    )[0]
    prompt = tmp_path / "prompt.mp3"
    timestamp = media.extract_prompt(source, cue.start, cue.end, 0.15, 0.25, prompt)
    stats = media.decoded_audio_stats(prompt)
    assert timestamp == pytest.approx(0.7)
    assert stats.leading_quiet >= 0.15 - 0.02
    assert stats.trailing_quiet >= 0.25 - 0.02
    assert timestamp + stats.leading_quiet == pytest.approx(0.91, abs=0.025)
    assert timestamp + stats.duration - stats.trailing_quiet == pytest.approx(2.18, abs=0.025)


@pytest.mark.integration
def test_exports_valid_pack_and_reimports_it(tmp_path: Path, monkeypatch) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "source.mp4"
    media.run(
        [
            media.ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=0x14283d:s=320x180:r=12:d=2",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=2",
            "-shortest",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            str(source),
        ],
        "Creating test video",
    )
    source_hash = file_hash(source)
    project = PackProject(
        title="Integration Pack",
        authors=["Test Creator"],
        readme="Generated by the integration test.",
        video_path=str(source),
        video_duration=2.0,
        head_padding=0.1,
        tail_padding=0.15,
        video_height=360,
        video_fps=12,
        source_url="https://youtu.be/abcdefghijk?si=tracking",
        segments=[
            Segment(0.2, 0.75, "First line", ["Alice"]),
            Segment(1.0, 1.55, "Second line", ["Bob"]),
        ],
    )

    updates = []
    cache_root = tmp_path / "receipts"
    commands = []
    command_started = media._command_started

    def record_command(command, description):
        commands.append((command, updates[-1].step if updates else None))
        return command_started(command, description)

    monkeypatch.setattr(media, "_command_started", record_command)
    result = PackExporter(media, cache_root=cache_root).export(
        project, tmp_path / "output", progress=updates.append,
    )
    messages = [update.message for update in updates]
    assert messages[0] == "Inspecting source video and audio..."
    assert any("Converting full video" in message for message in messages)
    encoding = [update for update in updates if update.live and update.position is not None]
    assert encoding
    assert encoding[-1].position == pytest.approx(2.0)
    assert 0 < encoding[-1].fraction < 1
    assert "frames" in encoding[-1].message
    plan = next(update.plan for update in updates if update.plan)
    observed_steps = list(dict.fromkeys(update.step for update in updates if update.step))
    assert observed_steps == [step.key for step in plan]
    assert "Creating pack icon..." in messages
    for index, speaker in enumerate(("Alice", "Bob"), start=1):
        for operation in (
            "Preparing prompt audio", "Preparing prompt still image",
            "Checking prompt audio duration, padding, and audibility",
            "Writing prompt caption and character metadata",
        ):
            assert any(
                message.startswith(operation) and f"Prompt {index}/2 - {speaker}" in message
                and project.segments[index - 1].caption in message for message in messages
            )
        for phase in ("Validating staged pack", "Revalidating published pack"):
            assert f"{phase}: fully decoding Ogg video and audio" in messages
            assert f"{phase}: prompt {index}/2: checking and decoding audio" in messages
            assert f"{phase}: prompt {index}/2: checking and decoding still image" in messages
    assert "Hashing staged file 11/11..." in messages
    assert "Creating ZIP: adding file 11/11..." in messages
    assert "Verifying published file 11/11..." in messages
    assert "Testing staged ZIP integrity and file inventory..." in messages
    assert "Testing published ZIP integrity and file inventory..." in messages
    assert messages.index("Hashing staged file 11/11...") < messages.index(
        "Creating ZIP: adding file 1/11..."
    ) < messages.index("Verifying published file 1/11...")
    assert messages[-1] == "Cleaning up export staging files..."
    assert result.pack_path.is_dir()
    assert result.zip_path and result.zip_path.is_file()
    expected_names = {
        "_pack_info.ini", "icon.png", "dub_video.ogv", "_backing_track.mp3",
        "001_Alice.mp3", "001_Alice.png", "001_Alice.txt",
        "002_Bob.mp3", "002_Bob.png", "002_Bob.txt",
        MANIFEST_NAME,
    }
    assert set(result.file_hashes) == expected_names
    assert result.file_hashes == {
        path.name: file_hash(path) for path in result.pack_path.iterdir()
    }
    with zipfile.ZipFile(result.zip_path) as archive:
        assert len(archive.infolist()) == len(expected_names)
        assert set(archive.namelist()) == {f"Integration Pack/{name}" for name in expected_names}
        for entry in archive.infolist():
            suffix = Path(entry.filename).suffix
            assert entry.compress_type == (
                zipfile.ZIP_STORED if suffix in {".ogv", ".mp3", ".png"}
                else zipfile.ZIP_DEFLATED
            )
            assert archive.read(entry) == (result.pack_path / Path(entry.filename).name).read_bytes()
    video = media.probe(result.pack_path / "dub_video.ogv")
    assert result.validation == {
        "status": "passed", "title": "Integration Pack", "clip_count": 2, "file_count": 11,
        "video": {
            "duration": video.duration, "width": video.width, "height": video.height,
            "fps": video.fps, "video_codec": "theora", "audio_codec": "vorbis",
        },
        "first_timestamp": 0.1, "last_timestamp": 0.9,
    }
    assert json.loads(PackValidator.report_json(result.validation)) == result.validation
    decode_evidence = {}
    for name in ("001_Alice.mp3", "002_Bob.mp3", "dub_video.ogv"):
        decodes = [
            (command, phase) for command, phase in commands
            if command[0] == media.ffmpeg and "-i" in command
            and Path(command[command.index("-i") + 1]).name == name
        ]
        phases = ["staged-validation", "published-validation"]
        if name.endswith(".mp3"):
            phases.insert(0, "prompts")
        assert [phase for _, phase in decodes] == phases
        decode_evidence[name] = [
            {"phase": phase, "command": command} for command, phase in decodes
        ]
        for command, phase in decodes:
            assert command.count("-i") == 1
            assert not {"-ss", "-t", "-to", "-frames:v", "-frames:a"}.intersection(command)
            input_path = Path(command[command.index("-i") + 1])
            assert (input_path == result.pack_path / name) == (phase == "published-validation")
            maps = [command[index + 1] for index, arg in enumerate(command) if arg == "-map"]
            if name.endswith(".mp3"):
                assert maps == (["0:a:0"] if phase == "prompts" else ["0:a:0", "0"])
                assert command.count("pipe:1") == 1
            else:
                assert maps == ["0"]
            if phase != "prompts":
                assert command[-3:] == ["-f", "null", os.devnull]
    assert any("without backing music" in warning for warning in result.warnings)
    assert media.audio_peak_dbfs(result.pack_path / "_backing_track.mp3") == float("-inf")
    metadata = read_config(result.pack_path / "001_Alice.txt")["data"]
    assert metadata["dub_timestamps"] == [0.1]
    assert metadata["caption"] == "First line"
    assert metadata["dub_characters"] == ["Alice"]
    assert metadata["image"] == "001_Alice.png"
    assert read_config(result.pack_path / "_pack_info.ini")["data"] == {
        "title": "Integration Pack", "authors": ["Test Creator"],
        "readme": "Generated by the integration test.", "icon": "icon.png",
    }

    with monkeypatch.context() as patch:
        def unexpected_conversion(*args, **kwargs):
            raise AssertionError("Unchanged video should be reused across exporter instances")

        patch.setattr(media, "convert_video", unexpected_conversion)
        repeated = PackExporter(media, cache_root=cache_root).export(project, tmp_path / "output")
    assert repeated.validation == result.validation
    assert repeated.file_hashes[MANIFEST_NAME] != result.file_hashes[MANIFEST_NAME]
    assert {name: digest for name, digest in repeated.file_hashes.items() if name != MANIFEST_NAME} == {
        name: digest for name, digest in result.file_hashes.items() if name != MANIFEST_NAME
    }
    assert read_manifest(repeated.pack_path).pack_id == project.pack_id

    original_duration = media.probe_audio_duration(result.pack_path / "001_Alice.mp3")
    project.title = "Retimed Integration Pack"
    project.segments[0].end = 0.95
    retimed = PackExporter(media).export(project, tmp_path / "retimed-output")
    retimed_duration = media.probe_audio_duration(retimed.pack_path / "001_Alice.mp3")
    assert retimed_duration > original_duration + 0.15

    imported = PackImporter(media).import_folder(result.pack_path).project
    assert imported.title == "Integration Pack"
    assert len(imported.segments) == 2
    assert imported.segments[0].audio_mode == "file"
    assert imported.segments[0].source_range_known
    assert (imported.segments[0].start, imported.segments[0].end) == (0.2, 0.75)
    assert imported.segments[0].recording_padding == (0.1, 0.15)
    assert imported.segments[0].id == project.segments[0].id
    assert imported.pack_id == project.pack_id
    assert imported.source_url == "https://www.youtube.com/watch?v=abcdefghijk"
    with pytest.raises(ValueError, match="contains source or project assets"):
        PackExporter(media).export(imported, result.pack_path.parent)

    imported.title = "output"
    imported.source_pack_path = ""
    with pytest.raises(ValueError, match="contains source or project assets"):
        PackExporter(media).export(imported, tmp_path)

    original_audio_hash = file_hash(result.pack_path / "001_Alice.mp3")
    original_image_hash = file_hash(result.pack_path / "001_Alice.png")
    imported.title = "Modified Integration Pack"
    imported.segments[0].caption = "Edited first line"
    updates.clear()
    modified = PackExporter(media).export(
        imported, tmp_path / "modified-output", create_zip=False, progress=updates.append,
    )
    messages = [update.message for update in updates]
    assert any("Preserving existing Ogg video" in message for message in messages)
    assert any("Preparing prompt audio\nPrompt 1/2 - Alice" in message for message in messages)
    assert not any("Creating ZIP" in message for message in messages)
    plan = next(update.plan for update in updates if update.plan)
    assert not any(step.kind in {"video-encode", "zip", "zip-check"} for step in plan)
    assert list(dict.fromkeys(update.step for update in updates if update.step)) == [
        step.key for step in plan
    ]
    assert modified.zip_path is None
    assert modified.validation["status"] == "passed"
    assert any("without backing music" in warning for warning in modified.warnings)
    assert read_config(modified.pack_path / "001_Alice.txt")["data"]["caption"] == (
        "Edited first line"
    )
    assert file_hash(modified.pack_path / "001_Alice.mp3") == original_audio_hash
    assert file_hash(modified.pack_path / "001_Alice.png") == original_image_hash
    assert read_config(modified.pack_path / "001_Alice.txt")["data"]["dub_timestamps"] == [0.1]

    recovered = PackImporter(media).import_zip(result.zip_path, tmp_path / "recovered").project
    dialogue_before = [segment.to_dict() for segment in recovered.segments]
    recovered_backing = tmp_path / "recovered-backing.mp3"
    media.convert_audio(source, recovered_backing, mono=False, duration=recovered.video_duration)
    recovered.backing_track_path = str(recovered_backing)
    repaired = PackExporter(media).export(recovered, tmp_path / "repaired-output")
    assert [segment.to_dict() for segment in recovered.segments] == dialogue_before
    assert media.decoded_audio_stats(repaired.pack_path / "_backing_track.mp3").has_activity
    assert not repaired.warnings
    assert file_hash(repaired.pack_path / "dub_video.ogv") == file_hash(result.pack_path / "dub_video.ogv")
    for name in ("001_Alice.mp3", "001_Alice.png", "001_Alice.txt", "002_Bob.txt"):
        assert file_hash(repaired.pack_path / name) == file_hash(result.pack_path / name)

    project.combine_segments([segment.id for segment in reversed(project.segments)])
    combined = PackExporter(media).export(project, tmp_path / "combined-output")
    assert combined.validation["status"] == "passed"
    assert combined.validation["clip_count"] == 1
    assert combined.validation["file_count"] == 8
    combined_metadata = read_config(combined.pack_path / "001_Alice.txt")["data"]
    assert combined_metadata["caption"] == "First line Second line"
    assert combined_metadata["dub_characters"] == ["Alice", "Bob"]
    assert combined_metadata["dub_timestamps"] == [0.1]
    combined_duration = media.probe_audio_duration(combined.pack_path / "001_Alice.mp3")
    assert combined_duration == pytest.approx(1.55 - 0.2 + 0.1 + 0.15, abs=0.05)
    assert file_hash(source) == source_hash
    (tmp_path / "export-validation-evidence.json").write_text(
        json.dumps({
            "pack_path": str(result.pack_path),
            "zip_path": str(result.zip_path),
            "validation": result.validation,
            "repeated_validation": repeated.validation,
            "file_hashes": result.file_hashes,
            "repeated_file_hashes": repeated.file_hashes,
            "decoded_commands": decode_evidence,
            "source_sha256_before": source_hash,
            "source_sha256_after": file_hash(source),
            "preserved_imported_audio_sha256": original_audio_hash,
            "preserved_imported_image_sha256": original_image_hash,
        }, indent=2) + "\n",
        encoding="utf-8",
    )


@pytest.mark.integration
def test_default_export_encodes_480p_and_higher_quality_remains_opt_in(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "source.mp4"
    media.run([
        media.ffmpeg, "-v", "error", "-y", "-f", "lavfi", "-i",
        "testsrc2=s=1280x720:r=30:d=1.5", "-f", "lavfi", "-i",
        "sine=frequency=440:sample_rate=48000:duration=1.5",
        "-shortest", "-c:v", "mpeg4", "-c:a", "aac", str(source),
    ], "Creating export quality fixture")
    project = PackProject(
        title="Quality", authors=["Tester"], video_path=str(source),
        segments=[Segment(0.3, 1.0, "Synthetic line", ["Tester"])],
    )
    exporter = PackExporter(media, cache_root=tmp_path / "receipts")
    fast = exporter.export(project, tmp_path / "output", create_zip=False)
    assert fast.validation["video"]["height"] == 480
    assert fast.validation["video"]["fps"] == 30
    project.video_height = 720
    high = exporter.export(project, tmp_path / "output", create_zip=False)
    assert high.validation["video"]["height"] == 720
    assert high.validation["video"]["fps"] == 30
    assert fast.file_hashes["dub_video.ogv"] != high.file_hashes["dub_video.ogv"]


@pytest.mark.integration
def test_backing_peak_checks_both_channels_without_mono_cancellation(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    stereo = tmp_path / "opposite-channels.wav"
    media.run(
        [
            media.ffmpeg, "-v", "error", "-f", "lavfi", "-i",
            "aevalsrc=0.1*sin(2*PI*440*t)|-0.1*sin(2*PI*440*t):s=44100:d=0.2",
            str(stereo),
        ],
        "Creating stereo backing fixture",
    )
    assert media.audio_peak_dbfs(stereo) == pytest.approx(-20, abs=0.02)


@pytest.mark.integration
def test_export_rejects_silent_and_out_of_bounds_source_content(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "silent.mp4"
    media.run(
        [
            media.ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=black:s=160x90:r=10:d=1",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=r=48000:cl=mono:d=1",
            "-shortest",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            str(source),
        ],
        "Creating silent test video",
    )
    silent = PackProject(
        title="Silent",
        authors=["Tester"],
        video_path=str(source),
        video_duration=10,
        segments=[Segment(0.1, 0.7, "Supposed line", ["Speaker"])],
    )
    with pytest.raises(RuntimeError, match="no audible content"):
        PackExporter(media).export(silent, tmp_path / "silent-output", create_zip=False)

    out_of_bounds = PackProject(
        title="Past EOF",
        authors=["Tester"],
        video_path=str(source),
        video_duration=10,
        segments=[Segment(2, 3, "Past the end", ["Speaker"])],
    )
    with pytest.raises(ValueError, match="after the video"):
        PackExporter(media).export(out_of_bounds, tmp_path / "eof-output", create_zip=False)
