from __future__ import annotations

import hashlib
import shutil
from pathlib import Path

import pytest

from choicer_voicer_pack_creator.config_format import read_config
from choicer_voicer_pack_creator.exporter import PackExporter
from choicer_voicer_pack_creator.media import MediaTools
from choicer_voicer_pack_creator.models import PackProject, Segment
from choicer_voicer_pack_creator.pack_io import PackImporter


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.mark.integration
def test_exports_valid_pack_and_reimports_it(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "source.mp4"
    media.run(
        [
            media.ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=0x14283d:s=320x180:r=12:d=2",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=2",
            "-shortest",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            str(source),
        ],
        "Creating test video",
    )
    project = PackProject(
        title="Integration Pack",
        authors=["Test Creator"],
        readme="Generated by the integration test.",
        video_path=str(source),
        video_duration=2.0,
        head_padding=0.1,
        tail_padding=0.15,
        video_height=360,
        video_fps=12,
        segments=[
            Segment(0.2, 0.75, "First line", ["Alice"]),
            Segment(1.0, 1.55, "Second line", ["Bob"]),
        ],
    )

    result = PackExporter(media).export(project, tmp_path / "output")
    assert result.pack_path.is_dir()
    assert result.zip_path and result.zip_path.is_file()
    assert result.validation["status"] == "passed"
    assert result.validation["clip_count"] == 2
    assert result.validation["file_count"] == 10
    metadata = read_config(result.pack_path / "001_Alice.txt")["data"]
    assert metadata["dub_timestamps"] == [0.1]
    assert metadata["caption"] == "First line"

    original_duration = media.probe_audio_duration(result.pack_path / "001_Alice.mp3")
    project.title = "Retimed Integration Pack"
    project.segments[0].end = 0.95
    retimed = PackExporter(media).export(project, tmp_path / "retimed-output")
    retimed_duration = media.probe_audio_duration(retimed.pack_path / "001_Alice.mp3")
    assert retimed_duration > original_duration + 0.15

    imported = PackImporter(media).import_folder(result.pack_path).project
    assert imported.title == "Integration Pack"
    assert len(imported.segments) == 2
    assert imported.segments[0].audio_mode == "file"
    with pytest.raises(ValueError, match="contains source or project assets"):
        PackExporter(media).export(imported, result.pack_path.parent)

    imported.title = "output"
    imported.source_pack_path = ""
    with pytest.raises(ValueError, match="contains source or project assets"):
        PackExporter(media).export(imported, tmp_path)

    original_audio_hash = file_hash(result.pack_path / "001_Alice.mp3")
    original_image_hash = file_hash(result.pack_path / "001_Alice.png")
    imported.title = "Modified Integration Pack"
    imported.segments[0].caption = "Edited first line"
    modified = PackExporter(media).export(imported, tmp_path / "modified-output")
    assert modified.validation["status"] == "passed"
    assert read_config(modified.pack_path / "001_Alice.txt")["data"]["caption"] == (
        "Edited first line"
    )
    assert file_hash(modified.pack_path / "001_Alice.mp3") == original_audio_hash
    assert file_hash(modified.pack_path / "001_Alice.png") == original_image_hash


@pytest.mark.integration
def test_export_rejects_silent_and_out_of_bounds_source_content(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "silent.mp4"
    media.run(
        [
            media.ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=black:s=160x90:r=10:d=1",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=r=48000:cl=mono:d=1",
            "-shortest",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            str(source),
        ],
        "Creating silent test video",
    )
    silent = PackProject(
        title="Silent",
        authors=["Tester"],
        video_path=str(source),
        video_duration=10,
        segments=[Segment(0.1, 0.7, "Supposed line", ["Speaker"])],
    )
    with pytest.raises(RuntimeError, match="no audible content"):
        PackExporter(media).export(silent, tmp_path / "silent-output", create_zip=False)

    out_of_bounds = PackProject(
        title="Past EOF",
        authors=["Tester"],
        video_path=str(source),
        video_duration=10,
        segments=[Segment(2, 3, "Past the end", ["Speaker"])],
    )
    with pytest.raises(ValueError, match="after the video"):
        PackExporter(media).export(out_of_bounds, tmp_path / "eof-output", create_zip=False)
