from __future__ import annotations

import hashlib
import shutil
from pathlib import Path

import pytest

from choicer_voicer_pack_creator.captions import refine_captions
from choicer_voicer_pack_creator.config_format import read_config
from choicer_voicer_pack_creator.exporter import PackExporter
from choicer_voicer_pack_creator.media import MediaTools
from choicer_voicer_pack_creator.models import PackProject, Segment, SourceCaption
from choicer_voicer_pack_creator.pack_io import PackImporter


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.mark.integration
def test_caption_handles_retain_source_audio_outside_subtitle_window(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "source.wav"
    media.run([
        media.ffmpeg, "-v", "error", "-y", "-f", "lavfi", "-i",
        "sine=frequency=440:sample_rate=48000:duration=1.27",
        "-af", "adelay=910,apad=whole_dur=5", str(source),
    ], "Creating audio that starts before and finishes after its caption")
    cue = refine_captions(
        [SourceCaption(1, 2, "Synthetic timing fixture", "YouTube creator (en)")],
        [(0.91, 2.18)], 5,
    )[0]
    prompt = tmp_path / "prompt.mp3"
    timestamp = media.extract_prompt(source, cue.start, cue.end, 0.15, 0.25, prompt)
    stats = media.decoded_audio_stats(prompt)
    assert timestamp == pytest.approx(0.7)
    assert stats.leading_quiet >= 0.15 - 0.02
    assert stats.trailing_quiet >= 0.25 - 0.02
    assert timestamp + stats.leading_quiet == pytest.approx(0.91, abs=0.025)
    assert timestamp + stats.duration - stats.trailing_quiet == pytest.approx(2.18, abs=0.025)


@pytest.mark.integration
def test_exports_valid_pack_and_reimports_it(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "source.mp4"
    media.run(
        [
            media.ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=0x14283d:s=320x180:r=12:d=2",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=2",
            "-shortest",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            str(source),
        ],
        "Creating test video",
    )
    project = PackProject(
        title="Integration Pack",
        authors=["Test Creator"],
        readme="Generated by the integration test.",
        video_path=str(source),
        video_duration=2.0,
        head_padding=0.1,
        tail_padding=0.15,
        video_height=360,
        video_fps=12,
        segments=[
            Segment(0.2, 0.75, "First line", ["Alice"]),
            Segment(1.0, 1.55, "Second line", ["Bob"]),
        ],
    )

    messages = []
    result = PackExporter(media).export(project, tmp_path / "output", progress=messages.append)
    assert messages[0] == "Inspecting source video and audio..."
    assert any("Converting video" in message for message in messages)
    assert "Creating pack icon..." in messages
    for index, speaker in enumerate(("Alice", "Bob"), start=1):
        assert f"Prompt {index}/2: preparing audio for {speaker}" in messages
        assert f"Prompt {index}/2: preparing still image..." in messages
        assert f"Prompt {index}/2: checking audio duration, padding, and audibility..." in messages
        for phase in ("Validating staged pack", "Revalidating published pack"):
            assert f"{phase}: fully decoding Ogg video and audio" in messages
            assert f"{phase}: prompt {index}/2: checking and decoding audio" in messages
            assert f"{phase}: prompt {index}/2: checking and decoding still image" in messages
    assert "Hashing staged file 10/10..." in messages
    assert "Creating ZIP: compressing file 10/10..." in messages
    assert "Verifying published file 10/10..." in messages
    assert "Testing staged ZIP integrity and file inventory..." in messages
    assert "Testing published ZIP integrity and file inventory..." in messages
    assert messages.index("Hashing staged file 10/10...") < messages.index(
        "Creating ZIP: compressing file 1/10..."
    ) < messages.index("Verifying published file 1/10...")
    assert messages[-1] == "Cleaning up export staging files..."
    assert result.pack_path.is_dir()
    assert result.zip_path and result.zip_path.is_file()
    assert result.validation["status"] == "passed"
    assert result.validation["clip_count"] == 2
    assert result.validation["file_count"] == 10
    assert any("without backing music" in warning for warning in result.warnings)
    assert media.audio_peak_dbfs(result.pack_path / "_backing_track.mp3") == float("-inf")
    metadata = read_config(result.pack_path / "001_Alice.txt")["data"]
    assert metadata["dub_timestamps"] == [0.1]
    assert metadata["caption"] == "First line"

    original_duration = media.probe_audio_duration(result.pack_path / "001_Alice.mp3")
    project.title = "Retimed Integration Pack"
    project.segments[0].end = 0.95
    retimed = PackExporter(media).export(project, tmp_path / "retimed-output")
    retimed_duration = media.probe_audio_duration(retimed.pack_path / "001_Alice.mp3")
    assert retimed_duration > original_duration + 0.15

    imported = PackImporter(media).import_folder(result.pack_path).project
    assert imported.title == "Integration Pack"
    assert len(imported.segments) == 2
    assert imported.segments[0].audio_mode == "file"
    with pytest.raises(ValueError, match="contains source or project assets"):
        PackExporter(media).export(imported, result.pack_path.parent)

    imported.title = "output"
    imported.source_pack_path = ""
    with pytest.raises(ValueError, match="contains source or project assets"):
        PackExporter(media).export(imported, tmp_path)

    original_audio_hash = file_hash(result.pack_path / "001_Alice.mp3")
    original_image_hash = file_hash(result.pack_path / "001_Alice.png")
    imported.title = "Modified Integration Pack"
    imported.segments[0].caption = "Edited first line"
    messages.clear()
    modified = PackExporter(media).export(
        imported, tmp_path / "modified-output", create_zip=False, progress=messages.append,
    )
    assert any("Preserving existing Ogg video" in message for message in messages)
    assert "Prompt 1/2: preparing audio for Alice" in messages
    assert not any("compressing file" in message for message in messages)
    assert modified.zip_path is None
    assert modified.validation["status"] == "passed"
    assert any("without backing music" in warning for warning in modified.warnings)
    assert read_config(modified.pack_path / "001_Alice.txt")["data"]["caption"] == (
        "Edited first line"
    )
    assert file_hash(modified.pack_path / "001_Alice.mp3") == original_audio_hash
    assert file_hash(modified.pack_path / "001_Alice.png") == original_image_hash

    recovered = PackImporter(media).import_zip(result.zip_path, tmp_path / "recovered").project
    dialogue_before = [segment.to_dict() for segment in recovered.segments]
    recovered_backing = tmp_path / "recovered-backing.mp3"
    media.convert_audio(source, recovered_backing, mono=False, duration=recovered.video_duration)
    recovered.backing_track_path = str(recovered_backing)
    repaired = PackExporter(media).export(recovered, tmp_path / "repaired-output")
    assert [segment.to_dict() for segment in recovered.segments] == dialogue_before
    assert media.decoded_audio_stats(repaired.pack_path / "_backing_track.mp3").has_activity
    assert not repaired.warnings
    assert file_hash(repaired.pack_path / "dub_video.ogv") == file_hash(result.pack_path / "dub_video.ogv")
    for name in ("001_Alice.mp3", "001_Alice.png", "001_Alice.txt", "002_Bob.txt"):
        assert file_hash(repaired.pack_path / name) == file_hash(result.pack_path / name)

    project.combine_segments([segment.id for segment in reversed(project.segments)])
    combined = PackExporter(media).export(project, tmp_path / "combined-output")
    assert combined.validation["status"] == "passed"
    assert combined.validation["clip_count"] == 1
    assert combined.validation["file_count"] == 7
    combined_metadata = read_config(combined.pack_path / "001_Alice.txt")["data"]
    assert combined_metadata["caption"] == "First line Second line"
    assert combined_metadata["dub_characters"] == ["Alice", "Bob"]
    assert combined_metadata["dub_timestamps"] == [0.1]
    combined_duration = media.probe_audio_duration(combined.pack_path / "001_Alice.mp3")
    assert combined_duration == pytest.approx(1.55 - 0.2 + 0.1 + 0.15, abs=0.05)


@pytest.mark.integration
def test_backing_peak_checks_both_channels_without_mono_cancellation(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    stereo = tmp_path / "opposite-channels.wav"
    media.run(
        [
            media.ffmpeg, "-v", "error", "-f", "lavfi", "-i",
            "aevalsrc=0.1*sin(2*PI*440*t)|-0.1*sin(2*PI*440*t):s=44100:d=0.2",
            str(stereo),
        ],
        "Creating stereo backing fixture",
    )
    assert media.audio_peak_dbfs(stereo) == pytest.approx(-20, abs=0.02)


@pytest.mark.integration
def test_export_rejects_silent_and_out_of_bounds_source_content(tmp_path: Path) -> None:
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        pytest.skip("FFmpeg is not available")
    media = MediaTools()
    source = tmp_path / "silent.mp4"
    media.run(
        [
            media.ffmpeg,
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=black:s=160x90:r=10:d=1",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=r=48000:cl=mono:d=1",
            "-shortest",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            str(source),
        ],
        "Creating silent test video",
    )
    silent = PackProject(
        title="Silent",
        authors=["Tester"],
        video_path=str(source),
        video_duration=10,
        segments=[Segment(0.1, 0.7, "Supposed line", ["Speaker"])],
    )
    with pytest.raises(RuntimeError, match="no audible content"):
        PackExporter(media).export(silent, tmp_path / "silent-output", create_zip=False)

    out_of_bounds = PackProject(
        title="Past EOF",
        authors=["Tester"],
        video_path=str(source),
        video_duration=10,
        segments=[Segment(2, 3, "Past the end", ["Speaker"])],
    )
    with pytest.raises(ValueError, match="after the video"):
        PackExporter(media).export(out_of_bounds, tmp_path / "eof-output", create_zip=False)
